services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mainnetwork

  web:
    build: .
    container_name: web
    depends_on:
      - db
    env_file:
      - .env.development
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - mainnetwork
    command:
      ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  pgdata:

networks:
  mainnetwork:
    driver: bridge
