"""Adding columns

Revision ID: 540b871dab6e
Revises: 694b6b9d1b1a
Create Date: 2025-03-02 19:43:42.565922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '540b871dab6e'
down_revision: Union[str, None] = '694b6b9d1b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('cost', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('output_tokens', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('agents', 'total_tokens')
    op.drop_column('agents', 'total_cost')
    op.add_column('projects', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'created_at')
    op.add_column('agents', sa.Column('total_cost', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('agents', sa.Column('total_tokens', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('agents', 'created_at')
    op.drop_column('agents', 'output_tokens')
    op.drop_column('agents', 'input_tokens')
    op.drop_column('agents', 'cost')
    # ### end Alembic commands ###
